### ISSUE TITLE
small fixes for scale scripts

### ISSUE THREAD

**Issue by tbeerman** [bbockelm/rucio-doma-tests#1]
- It would be better to use `update_rule` with a very small lifetime install of calling `delete_rule`.
- `purge_replicas` is not necessary since reaper runs in greedy mode.
- using `extract_scope` seems unnecessary in this case.
- why is `__g_rses` a global variable?

**Comment by bbockelm** [comment]
* `purge_replicas` is removed.
* `extract_scope` is heavily simplified.  I'd like the SCOPE to eventually not be a global (but a command-line argument) so I keep the abstraction there.
* `__g_rses` is a global since the set of RSEs that are enabled for a scale test should remain unchanged through the test's run.  I have to query each RSE individually so I am reluctant to pull this info from the server over and over.

That leave `update_rule`.  I'm not sure of any other way to guarantee that the full dataset is at least attempted (which may take a few hours once we get in the multi-TB range).  Since we wait until all replicas are purged before trying again, I'm a bit wary of too-short lifetimes.

That said, I did tweak it down to 4hrs.

**Comment by bbockelm** [comment]
@tbeerman - happy with all my changes?  OK to close this out?
